const express=require('express');const {Pool}=require('pg');const cors=require('cors');const path=require('path');
const app=express();app.use(cors());app.use(express.json());
app.use(express.static(__dirname));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
app.get('/api/leads',async(req,res)=>{try{const r=await pool.query('SELECT * FROM leads ORDER BY id DESC');res.json(r.rows);}catch(e){res.json([])}});
app.get('/api/stats',async(req,res)=>{try{const r=await pool.query('SELECT COUNT(*) as total, AVG(score_ia) as media FROM leads');const g=await pool.query("SELECT COUNT(*) as c FROM leads WHERE status='proposta'");res.json({total:parseInt(r.rows[0].total),whatsapp:parseInt(r.rows[0].total),media:Math.round(r.rows[0].media||65),gargalo:parseInt(g.rows[0].c)});}catch(e){res.json({total:0,whatsapp:0,media:0,gargalo:0})}});
app.post('/api/leads',async(req,res)=>{try{const{nome,whatsapp}=req.body;const score=Math.floor(Math.random()*30+60);const r=await pool.query('INSERT INTO leads(nome,whatsapp,status,score_ia) VALUES($1,$2,$3,$4) RETURNING *',[nome,whatsapp,'novo',score]);res.json(r.rows[0]);}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/leads/:id',async(req,res)=>{try{const{id}=req.params;const{status}=req.body;await pool.query('UPDATE leads SET status=$1 WHERE id=$2',[status,id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/leads/:id',async(req,res)=>{try{await pool.query('DELETE FROM leads WHERE id=$1',[req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({error:e.message})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
const PORT=process.env.PORT||10000;app.listen(PORT,()=>console.log('CRM v3.3 LIVE'));
