const express=require('express');const{Pool}=require('pg');const cors=require('cors');const path=require('path');const app=express();app.use(cors());app.use(express.json({limit:'10mb'}));app.use(express.static(path.join(__dirname)));const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false}});
function scoreIA(n,w){let s=65;const l=n.toLowerCase();if(l.includes('igreja')||l.includes('batista')||l.includes('franquia')||l.includes('bem protege')||l.includes('hilux')||l.includes('ekklesia'))s+=25;if(w?.length>=11)s+=10;return Math.min(98,Math.max(15,s));}
app.get('/api/leads',async(r,s)=>{try{const q=await pool.query('SELECT * FROM leads ORDER BY id DESC');s.json(q.rows)}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/leads',async(r,s)=>{const{nome,whatsapp,observacao='',valor=0,cnpj='',cpf='',email='',endereco='',tipo='lead',origem='manual'}=r.body;if(!nome||!whatsapp)return s.status(400).json({error:'obrigatorio'});const sc=scoreIA(nome,whatsapp);try{const q=await pool.query('INSERT INTO leads (nome,whatsapp,status,score_ia,observacao,valor,cnpj,cpf,email,endereco,tipo,origem) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *',[nome,whatsapp,'novo',sc,observacao,valor,cnpj,cpf,email,endereco,tipo,origem]);s.json(q.rows[0])}catch(e){s.status(500).json({error:e.message})}});
app.patch('/api/leads/:id',async(r,s)=>{const{status,observacao,valor,cnpj,cpf,email,endereco,tipo}=r.body;try{if(status)await pool.query('UPDATE leads SET status=$1 WHERE id=$2',[status,r.params.id]);if(observacao!==undefined)await pool.query('UPDATE leads SET observacao=$1 WHERE id=$2',[observacao,r.params.id]);if(valor!==undefined)await pool.query('UPDATE leads SET valor=$1 WHERE id=$2',[valor,r.params.id]);if(cnpj!==undefined)await pool.query('UPDATE leads SET cnpj=$1 WHERE id=$2',[cnpj,r.params.id]);if(cpf!==undefined)await pool.query('UPDATE leads SET cpf=$1 WHERE id=$2',[cpf,r.params.id]);if(email!==undefined)await pool.query('UPDATE leads SET email=$1 WHERE id=$2',[email,r.params.id]);if(endereco!==undefined)await pool.query('UPDATE leads SET endereco=$1 WHERE id=$2',[endereco,r.params.id]);if(tipo!==undefined)await pool.query('UPDATE leads SET tipo=$1 WHERE id=$2',[tipo,r.params.id]);const q=await pool.query('SELECT * FROM leads WHERE id=$1',[r.params.id]);s.json(q.rows[0])}catch(e){s.status(500).json({error:e.message})}});
app.delete('/api/leads/:id',async(r,s)=>{try{await pool.query('DELETE FROM leads WHERE id=$1',[r.params.id]);s.json({ok:true})}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/claude',async(r,s)=>{const{mensagem,leads}=r.body;const treino=r.body.treino||'';if(process.env.ANTHROPIC_API_KEY){try{const resp=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':process.env.ANTHROPIC_API_KEY,'Content-Type':'application/json','anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-3-5-sonnet-20241022',max_tokens:800,system:`Você é IA Ekklésia 4 pilares. Treino: ${treino.slice(0,4000)} Leads: ${JSON.stringify(leads).slice(0,3000)}`,messages:[{role:'user',content:mensagem}]})});const d=await resp.json();return s.json({resposta:d.content?.[0]?.text})}catch(e){return s.json({resposta:'Erro Claude:'+e.message})}}s.json({resposta:`Ekklésia tem ${leads?.length||0} leads, R$${leads?.reduce((a,b)=>a+Number(b.valor||0),0)||0}. 4 pilares ativos!`})});
async function analisarEMover(leadId, mensagemCliente, leadsAtuais){
  if(!process.env.ANTHROPIC_API_KEY) return {novoStatus:null};
  const prompt=`IA Ekklésia. Mensagem:"${mensagemCliente}" Lead:${JSON.stringify(leadsAtuais.find(l=>l.id==leadId))} REGRAS: fechei/pagar/pix/boleto/aprovado/fechado/manda contrato = "fechado". quanto custa/valor/como funciona/interesse/modelo/ano carro = "qualificado". marcar/reunião/call/proposta/humano/atendente = "proposta". SÓ JSON {"novoStatus":"fechado|proposta|qualificado|novo","motivo":"curto"}`;
  try{
    const resp=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':process.env.ANTHROPIC_API_KEY,'Content-Type':'application/json','anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-3-5-sonnet-20241022',max_tokens:200,messages:[{role:'user',content:prompt}]})});
    const data=await resp.json();const texto=data.content?.[0]?.text||'{}';const json=JSON.parse(texto.match(/\{.*\}/s)?.[0]||'{}');
    if(json.novoStatus){await pool.query('UPDATE leads SET status=$1 WHERE id=$2',[json.novoStatus,leadId]);return json;}
  }catch(e){console.log('Erro IA',e.message)}return{novoStatus:null}
}
app.post('/api/webhook/whatsapp',async(req,res)=>{const{whatsapp,mensagem}=req.body;if(!whatsapp||!mensagem)return res.json({ok:false});try{const q=await pool.query('SELECT * FROM leads WHERE whatsapp LIKE $1 ORDER BY id DESC LIMIT 1',['%'+whatsapp.replace(/\D/g,'').slice(-8)+'%']);const lead=q.rows[0];if(!lead)return res.json({ok:false});const resultado=await analisarEMover(lead.id,mensagem,[lead]);res.json({ok:true,moveu:resultado})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/teste-ia-mover',async(req,res)=>{const{leadId,mensagem}=req.body;const all=await pool.query('SELECT * FROM leads');const r=await analisarEMover(leadId,mensagem,all.rows);const novo=await pool.query('SELECT * FROM leads WHERE id=$1',[leadId]);res.json({resultado:r,lead:novo.rows[0]})});
app.get('/',(r,s)=>s.sendFile(path.join(__dirname,'index.html')));app.listen(process.env.PORT||10000,()=>console.log('Ekklésia v8 LIVE'));
